import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../components/Navbar'
import Profile from '../components/Profile'
import About from '../components/About'
import Contact from '../components/Contact'
import Skills from '../components/Skills/Skills'
import Projects from '../components/Projects/Projects'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Anubhab Patra|Front-end Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <Profile/>
      <About/>
      <Skills/>
      <Projects/>
      <Contact/>
      
    </div>
  )
}
